;;; leuven-dark-theme.el --- Awesome Emacs color theme on white background

;; Copyright (C) 2003-2015 Free Software Foundation, Inc.

;; URL: https://github.com/fniessen/emacs-leuven-dark-theme
;; Version: 20150213.1421
;; Keywords: color theme

;; This file is part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This elegant Org-enhancing color theme "leuven-dark" ROCKS!
;; ... and not just for Org mode.
;;
;; To use it, put the following in your Emacs configuration file:
;;
;;   (load-theme 'leuven-dark t)
;;
;; Requirements: Emacs 24.

;;; Code:

(deftheme leuven-dark
  "Face colors with a light background.
Basic, Font Lock, Isearch, Gnus, Message, Org mode, Diff, Ediff,
Flyspell, Semantic, and Ansi-Color faces are included -- and much
more...")

(let ((class '((class color) (min-colors 89)))

      ;; Leuven generic colors.
      (cae "#CAE682")
      (string-color "#95e454")
      (builtin-color "#E5786D")
      (type-color "PaleGreen")
      (std-highlight '(:foreground nil :background "dark slate blue"))
      (side '(:foreground "gray70" :background "gray18"))
      (cancel '(:slant italic :strike-through t :foreground "gray55"))
      (clock-line '(:box (:line-width 1 :color "#335EA8") :foreground "#F6F3E8" :background "#333366"))
      (code-block-begin '(:foreground "SlateGray3" :box '(:style released-button :line-width 1 :color "gray2")))
      (code-block-end '(:foreground "SlateGray3" :box '(:style released-button :line-width 1 :color "gray2")))
      (code-block '(:foreground "gray60" :background "grey18"))
      (code-inline '(:foreground "grey70"))
      (column '(:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "LightGoldenrod1" :background "gray30"))
      (diff-added '(:foreground "#008000" :background "forest green"))
      (diff-changed '(:foreground "SteelBlue1" :background "PaleGreen"))
      (diff-header '(:foreground "tomato2" :background "SlateGray3"))
      (diff-hunk-header '(:foreground "pink" :background "magenta4"))
      (diff-none '(:foreground "gray33"))
      (diff-removed '(:foreground "tomato2" :background "tomato2"))
      (directory '(:weight bold :foreground "SteelBlue1" :background "SlateGray3"))
      (highlight-line '(:background "gray18")) ; #F5F5F5
      (highlight-line-gnus '(:background "#99968B")) ; defined in `gnus-leuven.el'
      (link '(:weight normal :underline t :foreground "#8AC6F2"))
      (mail-header-name '(:family "Sans Serif" :weight normal :foreground "gray50"))
      (mail-header-other '(:family "Sans Serif" :slant normal :foreground "gray50"))
      (mail-read '(:weight normal :foreground "gray50"))
      (mail-ticked '(:weight bold :foreground "tomato2"))
      (mail-to '(:family "Sans Serif" :underline nil :foreground "#8AC6F2"))
      (mail-unread '(:weight bold :foreground "#F6F3E8"))
      (marked-line '(:weight bold :foreground "pink" :background "pink"))
      (match '(:weight bold :background "#333366")) ; occur patterns
      (ol1 '(:height 1.2 :weight bold :overline nil :foreground "#CAE682" :background nil))
      (ol2 '(:height 1.1 :weight bold :overline nil :foreground "sandy brown" :background nil))
      (ol3 '(:height 1.0 :weight bold :foreground "aquamarine" :background nil))
      (ol4 '(:height 1.0 :weight bold :slant normal :foreground "gold"))
      (ol5 '(:height 1.0 :weight bold :slant normal :foreground "CAE682"))
      (ol6 '(:height 1.0 :weight bold :slant italic :foreground "sandy brown"))
      (ol7 '(:height 1.0 :weight bold :slant italic :foreground "aquamarine"))
      (ol8 '(:height 1.0 :weight bold :slant italic :foreground "gold"))
      (paren-matched '(:background "SteelBlue1"))
      (paren-unmatched '(:underline "pink" :foreground nil :background "magenta3"))
      (region '(:background "gray25"))
      (shadow '(:foreground "gray70"))
      (string '(:foreground "#95E454")) ; or #D0372D
      (subject '(:family "Sans Serif" :weight bold :foreground "#F6F3E8"))
      (symlink '(:foreground "SteelBlue2"))
      (tab '(:foreground "gray40" :background "#242424"))
      (volatile-highlight '(:underline nil :background "gray22"))
      (vc-branch '(:box (:line-width 1 :color "#CAE682") :foreground "#F6F3E8" :background "forest green")))

  (custom-theme-set-faces 'leuven-dark
   `(default ((,class (:foreground "#f6f3e8" :background "#242424"))))
   `(bold ((,class (:weight bold :foreground "#F6F3E8"))))
   `(bold-italic ((,class (:weight bold :slant italic :foreground "#F6F3E8"))))
   `(italic ((,class (:slant italic :foreground "gray95"))))
   `(underline ((,class (:underline t))))
   `(cursor ((,class (:background "light green"))))

   ;; Highlighting faces.
   `(fringe ((,class ,side)))
   `(highlight ((,class ,volatile-highlight)))
   `(region ((,class ,region)))
   `(secondary-selection ((,class ,match))) ; used by Org-mode for highlighting matched entries and keywords
   `(isearch ((,class (:weight bold :underline "#FFC125" :foreground nil :background "SlateGray3"))))
   `(isearch-fail ((,class (:weight bold :foreground "#F6F3E8" :background "plum"))))
   `(lazy-highlight ((,class (:underline "#FFC125" :background "#384048")))) ; isearch others
   `(trailing-whitespace ((,class (:background "pink"))))
   `(whitespace-hspace ((,class (:foreground "gray40")))) ; see also `nobreak-space'
   `(whitespace-indentation ((,class ,tab)))
   `(whitespace-line ((,class (:foreground "tomato2" :background "gray18"))))
   `(whitespace-tab ((,class ,tab)))
   `(whitespace-trailing ((,class (:foreground "gray50" :background "pink"))))

   ;; Mode line faces.
   `(mode-line ((,class (:box (:line-width 1 :color "gray70") :foreground "SteelBlue1" :background "#335EA8"))))
   `(mode-line-inactive ((,class (:box (:line-width 1 :color "gray60") :foreground "gray24" :background "gray50"))))
   `(mode-line-buffer-id ((,class (:weight bold :foreground "#242424"))))
   `(mode-line-emphasis ((,class (:weight bold :foreground "#242424"))))
   `(mode-line-highlight ((,class (:foreground "gray20"))))

   ;; Escape and prompt faces.
   `(minibuffer-prompt ((,class (:weight bold :foreground "#F6F3E8" :background "gold"))))
   `(minibuffer-noticeable-prompt ((,class (:weight bold :foreground "#F6F3E8" :background "gold"))))
   `(escape-glyph ((,class (:foreground "#8AC6F2"))))
   `(error ((,class (:foreground "pink"))))
   `(warning ((,class (:weight bold :foreground "#E65C00"))))
   `(success ((,class (:foreground "#95e454"))))

   ;; Font lock faces.
   `(font-lock-builtin-face ((,class (:foreground ,builtin-color))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "SlateGray3")))) ; #696969
   `(font-lock-comment-face ((,class (:slant italic :foreground "SlateGray3")))) ; #696969
   `(font-lock-constant-face ((,class (:foreground "plum"))))
   `(font-lock-doc-face ((,class (:foreground ,string-color))))
   ;; `(font-lock-doc-string-face ((,class (:foreground "#008000")))) ; XEmacs only, but is used for HTML exports from org2html (and not interactively)
   `(font-lock-function-name-face ((,class (:weight normal :foreground ,cae))))
   `(font-lock-keyword-face ((,class (:bold nil :foreground "SteelBlue1")))) ; #3654DC
   `(font-lock-preprocessor-face ((,class (:foreground "#808080"))))
   `(font-lock-regexp-grouping-backslash ((,class (:weight bold :inherit nil))))
   `(font-lock-regexp-grouping-construct ((,class (:weight bold :inherit nil))))
   `(font-lock-string-face ((,class ,string)))
   `(font-lock-type-face ((,class (:weight normal :foreground ,cae))))
   `(font-lock-variable-name-face ((,class (:weight normal :foreground "#CAE682")))) ; #800080
   `(font-lock-warning-face ((,class (:weight bold :foreground "#CCAA8F"))))

   ;; Button and link faces.
   `(link ((,class ,link)))
   `(link-visited ((,class (:underline t :foreground "tomato2"))))
   `(button ((,class (:underline t :foreground "#8AC6F2"))))
   `(header-line ((,class (:weight bold :underline "#F6F3E8" :overline "#F6F3E8" :foreground "#F6F3E8" :background "gray18"))))

   ;; Gnus faces.
   `(gnus-button ((,class (:weight normal))))
   `(gnus-cite-attribution-face ((,class (:foreground "#5050B0"))))
   `(gnus-cite-face-1 ((,class (:foreground "#5050B0"))))
   `(gnus-cite-face-10 ((,class (:foreground "tomato2"))))
   `(gnus-cite-face-2 ((,class (:foreground "plum"))))
   `(gnus-cite-face-3 ((,class (:foreground "#4BC98A"))))
   `(gnus-cite-face-4 ((,class (:foreground "tomato2"))))
   `(gnus-cite-face-5 ((,class (:foreground "SteelBlue1"))))
   `(gnus-cite-face-6 ((,class (:foreground "tomato2"))))
   `(gnus-cite-face-7 ((,class (:foreground "#5050B0"))))
   `(gnus-cite-face-8 ((,class (:foreground "plum"))))
   `(gnus-cite-face-9 ((,class (:foreground "#4BC98A"))))
   `(gnus-emphasis-bold ((,class (:weight bold))))
   `(gnus-emphasis-highlight-words ((,class (:foreground "gray20" :background "#F6F3E8"))))
   `(gnus-group-mail-1 ((,class (:weight bold :foreground "pink"))))
   `(gnus-group-mail-1-empty ((,class (:foreground "#5050B0"))))
   `(gnus-group-mail-2 ((,class (:weight bold :foreground "tomato2"))))
   `(gnus-group-mail-2-empty ((,class (:foreground "plum"))))
   `(gnus-group-mail-3 ((,class (:weight bold :foreground "#F6F3E8"))))
   `(gnus-group-mail-3-empty ((,class ,mail-read)))
   `(gnus-group-mail-low ((,class ,cancel)))
   `(gnus-group-mail-low-empty ((,class ,cancel)))
   `(gnus-group-news-1 ((,class (:weight bold :foreground "pink"))))
   `(gnus-group-news-1-empty ((,class (:foreground "#5050B0"))))
   `(gnus-group-news-2 ((,class (:weight bold :foreground "tomato2"))))
   `(gnus-group-news-2-empty ((,class (:foreground "plum"))))
   `(gnus-group-news-3 ((,class (:weight bold :foreground "#F6F3E8"))))
   `(gnus-group-news-3-empty ((,class (:foreground "#808080"))))
   `(gnus-group-news-4 ((,class (:weight bold :foreground "tomato2"))))
   `(gnus-group-news-4-empty ((,class (:foreground "tomato2"))))
   `(gnus-group-news-5 ((,class (:weight bold :foreground "pink"))))
   `(gnus-group-news-5-empty ((,class (:foreground "SteelBlue1"))))
   `(gnus-group-news-6 ((,class (:weight bold :foreground "gray50"))))
   `(gnus-group-news-6-empty ((,class (:foreground "#808080"))))
   `(gnus-header-content ((,class ,mail-header-other)))
   `(gnus-header-from ((,class (:family "Sans Serif" :foreground "#F6F3E8"))))
   `(gnus-header-name ((,class ,mail-header-name)))
   `(gnus-header-newsgroups ((,class (:family "Sans Serif" :foreground "#64A8D8"))))
   `(gnus-header-subject ((,class ,subject)))
   `(gnus-picon ((,class (:foreground "gray20" :background "#242424"))))
   `(gnus-picon-xbm ((,class (:foreground "gray20" :background "#242424"))))
   `(gnus-server-closed ((,class (:slant italic :foreground "SteelBlue1" :background "#242424"))))
   `(gnus-server-denied ((,class (:weight bold :foreground "pink" :background "#242424"))))
   `(gnus-server-opened ((,class (:family "Sans Serif" :foreground "#242424" :foreground "#64A8D8"))))
   `(gnus-signature ((,class (:slant italic :foreground "gray50"))))
   `(gnus-splash ((,class (:foreground "pink"))))
   `(gnus-summary-cancelled ((,class ,cancel)))
   `(gnus-summary-high-ancient ((,class (:weight normal :foreground "#808080" :background "LightGoldenrod1"))))
   `(gnus-summary-high-read ((,class (:weight normal :foreground "#999999" :background "LightGoldenrod1"))))
   `(gnus-summary-high-ticked ((,class ,mail-ticked)))
   `(gnus-summary-high-unread ((,class (:weight bold :foreground "#F6F3E8" :background "#FFFFCC"))))
   `(gnus-summary-low-ancient ((,class (:slant italic :foreground "gray55"))))
   `(gnus-summary-low-read ((,class (:slant italic :foreground "#999999" :background "gray30"))))
   `(gnus-summary-low-ticked ((,class ,mail-ticked)))
   `(gnus-summary-low-unread ((,class (:slant italic :foreground "#F6F3E8"))))
   `(gnus-summary-normal-ancient ((,class ,mail-read)))
   `(gnus-summary-normal-read ((,class ,mail-read)))
   `(gnus-summary-normal-ticked ((,class ,mail-ticked)))
   `(gnus-summary-normal-unread ((,class ,mail-unread)))
   `(gnus-summary-selected ((,class (:foreground "#242424" :background "light blue"))))
   `(gnus-x-face ((,class (:foreground "#F6F3E8" :background "#242424"))))

   ;; Message faces.
   `(message-header-name ((,class ,mail-header-name)))
   `(message-header-cc ((,class ,mail-to)))
   `(message-header-other ((,class ,mail-header-other)))
   `(message-header-subject ((,class ,subject)))
   `(message-header-to ((,class ,mail-to)))
   `(message-cited-text ((,class (:foreground "#5050B0"))))
   `(message-separator ((,class (:family "Sans Serif" :weight normal :foreground "gray50"))))
   `(message-header-newsgroups ((,class (:family "Sans Serif" :foreground "#64A8D8"))))
   `(message-header-xheader ((,class ,mail-header-other)))
   `(message-mml ((,class (:foreground "#CAE682"))))

   ;; Diff.
   `(diff-added ((,class ,diff-added)))
   `(diff-changed ((,class ,diff-changed)))
   `(diff-context ((,class ,diff-none)))
   `(diff-file-header ((,class ,diff-header)))
   `(diff-file1-hunk-header ((,class (:foreground "#CC99CC" :background "grey18"))))
   `(diff-file2-hunk-header ((,class (:foreground "#95E454" :background "grey18"))))
   `(diff-function ((,class (:foreground "light gray"))))
   `(diff-header ((,class ,diff-header)))
   `(diff-hunk-header ((,class ,diff-hunk-header)))
   `(diff-index ((,class ,diff-header)))
   `(diff-indicator-added ((,class (:background "forest green"))))
   `(diff-indicator-changed ((,class (:background "#CC99CC"))))
   `(diff-indicator-removed ((,class (:background "pink"))))
   `(diff-refine-change ((,class (:background "PaleGreen"))))
   `(diff-removed ((,class ,diff-removed)))

   ;; SMerge.
   `(smerge-refined-change ((,class (:background "gray50"))))

   ;; Ediff.
   `(ediff-current-diff-A ((,class (:foreground "gray33" :background "tomato2"))))
   `(ediff-current-diff-B ((,class (:foreground "gray33" :background "forest green"))))
   `(ediff-current-diff-C ((,class (:foreground "#F6F3E8" :background "PaleGreen"))))
   `(ediff-even-diff-A ((,class (:foreground "#F6F3E8" :background "light grey"))))
   `(ediff-even-diff-B ((,class (:foreground "#F6F3E8" :background "light grey"))))
   `(ediff-fine-diff-A ((,class (:foreground "tomato2" :background "pink"))))
   `(ediff-fine-diff-B ((,class (:foreground "#008000" :background "forest green"))))
   `(ediff-odd-diff-A ((,class (:foreground "#F6F3E8" :background "light grey"))))
   `(ediff-odd-diff-B ((,class (:foreground "#F6F3E8" :background "light grey"))))

   ;; Flyspell.
   (if (version< emacs-version "24.4")
       `(flyspell-duplicate ((,class (:underline "#008000" :inherit nil))))
     `(flyspell-duplicate ((,class (:underline (:style wave :color "#008000") :inherit nil)))))
   (if (version< emacs-version "24.4")
       `(flyspell-incorrect ((,class (:underline "pink" :inherit nil))))
     `(flyspell-incorrect ((,class (:underline (:style wave :color "pink") :inherit nil)))))

   ;; ;; Semantic faces.
   ;; `(semantic-decoration-on-includes ((,class (:underline ,cham-4))))
   ;; `(semantic-decoration-on-private-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-protected-members-face ((,class (:background ,alum-2))))
   ;; `(semantic-decoration-on-unknown-includes ((,class (:background ,choc-3))))
   ;; `(semantic-decoration-on-unparsed-includes ((,class (:underline ,orange-3))))
   ;; `(semantic-tag-boundary-face ((,class (:overline ,blue-1))))
   ;; `(semantic-unmatched-syntax-face ((,class (:underline ,red-1))))

   `(Info-title-1-face ((,class ,ol1)))
   `(Info-title-2-face ((,class ,ol2)))
   `(Info-title-3-face ((,class ,ol3)))
   `(Info-title-4-face ((,class ,ol4)))
   `(ac-completion-face ((,class (:underline nil :foreground "#4BC98A")))) ; like Google
   `(ace-jump-face-foreground ((,class (:foreground "#F6F3E8" :background "LightGoldenrod1"))))
   `(ahs-face ((,class (:background "light yellow"))))
   `(ahs-definition-face ((,class (:weight bold :background "light yellow"))))
   `(ahs-plugin-defalt-face ((,class (:background "pink"))))
   `(auto-dim-other-buffers-face ((,class (:background "gray20"))))
   `(bbdb-company ((,class (:slant italic :foreground "SteelBlue1"))))
   `(bbdb-field-name ((,class (:weight bold :foreground "SteelBlue1"))))
   `(bbdb-field-value ((,class (:foreground "SteelBlue1"))))
   `(bbdb-name ((,class (:underline t :foreground "tomato2"))))
   `(bmkp-light-autonamed ((,class (:background "SteelBlue1"))))
   `(bmkp-light-fringe-autonamed ((,class (:background "light gray"))))
   `(bmkp-light-fringe-non-autonamed ((,class (:background "forest green"))))
   `(bmkp-light-non-autonamed ((,class (:background "forest green"))))
   `(browse-kill-ring-separator-face ((,class (:weight bold :foreground "SlateGray3"))))
   `(calendar-month-header ((,class (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
   `(calendar-today ((,class (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
   `(calendar-weekday-header ((,class (:weight bold :foreground "LightGoldenrod1"))))
   `(calendar-weekend-header ((,class (:weight bold :foreground "#CC99CC"))))
   `(cfw:face-annotation ((,class (:foreground "#95e454" :background "pink"))))
   `(cfw:face-day-title ((,class (:foreground "gray50"))))
   `(cfw:face-default-content ((,class (:foreground "#64A8D8"))))
   `(cfw:face-default-day ((,class (:weight bold))))
   `(cfw:face-disable ((,class (:foreground "light gray"))))
   `(cfw:face-grid ((,class (:foreground "gray30"))))
   `(cfw:face-header ((,class (:foreground "LightGoldenrod1" :background "#242424" :weight bold))))
   `(cfw:face-holiday ((,class (:foreground "#777777" :background "#FFC125"))))
   `(cfw:face-periods ((,class (:foreground "#242424" :background "light blue" :slant italic))))
   `(cfw:face-saturday ((,class (:foreground "#CC99CC" :background "#242424" :weight bold))))
   `(cfw:face-select ((,class (:foreground "aquamarine" :background "gray24"))))
   `(cfw:face-sunday ((,class (:foreground "#CC99CC" :background "#242424" :weight bold))))
   `(cfw:face-title ((,class (:height 2.0 :foreground "gray50" :weight bold :inherit variable-pitch))))
   `(cfw:face-today ((,class (:foreground "#4F4A3D" :background "#FFFFCC"))))
   `(cfw:face-today-title ((,class (:foreground "aquamarine" :background "#FFFFCC"))))
   `(cfw:face-toolbar ((,class (:background "#242424"))))
   `(cfw:face-toolbar-button-off ((,class (:foreground "LightGoldenrod" :background "#242424"))))
   `(cfw:face-toolbar-button-on ((,class (:foreground "gray60" :background "SlateGray3"))))
   `(change-log-date ((,class (:foreground "#CC99CC"))))
   `(change-log-file ((,class (:weight bold :foreground "SteelBlue1"))))
   `(change-log-list ((,class (:foreground "cyan"))))
   `(change-log-name ((,class (:foreground "#008000"))))
   `(circe-highlight-all-nicks-face ((,class (:foreground "SteelBlue1" :background "#F0F0F0")))) ; other nick names
   `(circe-highlight-nick-face ((,class (:foreground "#CAE682" :background "#F0F0F0")))) ; messages with my nick cited
   `(circe-my-message-face ((,class (:foreground "gray50" :background "#F0F0F0"))))
   `(circe-originator-face ((,class (:foreground "SteelBlue1"))))
   `(circe-prompt-face ((,class (:foreground "pink"))))
   `(circe-server-face ((,class (:foreground "SteelBlue1"))))
   `(comint-highlight-input ((,class (:weight bold :foreground "SteelBlue1" :inherit nil))))
   `(comint-highlight-prompt ((,class (:weight bold :foreground "SteelBlue1" :inherit nil))))
   `(company-preview-common ((,class (:foreground "#4BC98A" :background "gray18")))) ; same background as highlight-line
   `(company-scrollbar-bg ((,class (:background "gray24"))))
   `(company-scrollbar-fg ((,class (:background "gray20"))))
   `(company-tooltip ((,class (:inherit default :background "gray18"))))
   `(company-tooltip-annotation ((,class (:inherit default))))
   `(company-tooltip-common ((,class (:inherit font-lock-constant-face))))
   `(company-tooltip-common-selection ((,class (:foreground "tomato2" :background "gray10"))))
   `(company-tooltip-selection ((,class (:inherit font-lock-function-name-face))))
   `(compare-windows ((,class (:background "#384048"))))
   `(compilation-error ((,class (:weight bold :foreground "pink")))) ; Used for grep error messages.
   `(compilation-info ((,class (:weight bold :foreground "#64A8D8")))) ; Used for grep hits.
   `(compilation-line-number ((,class (:weight bold :foreground "pink"))))
   `(compilation-warning ((,class (:weight bold :foreground "#E65C00"))))
   `(compilation-mode-line-exit ((,class (:weight bold :foreground "#95e454")))) ; :exit[matched]
   `(compilation-mode-line-fail ((,class (:weight bold :foreground "violet")))) ; :exit[no match]
   `(compilation-mode-line-run ((,class (:weight bold :foreground "#E65C00")))) ; :run
   `(css-property ((,class (:foreground "#CAE682"))))
   `(css-selector ((,class (:weight bold :foreground "SteelBlue1"))))
   `(custom-button ((,class (:box (:line-width 2 :style released-button) :foreground "#F6F3E8" :background "dark gray"))))
   `(custom-button-mouse ((,class (:box (:line-width 2 :style released-button) :foreground "#F6F3E8" :background "grey90"))))
   `(custom-button-pressed ((,class (:box (:line-width 2 :style pressed-button) :foreground "#F6F3E8" :background "light grey"))))
   `(custom-button-pressed-unraised ((,class (:underline t :foreground "#C99CC"))))
   `(custom-button-unraised ((,class (:underline t))))
   `(custom-changed ((,class (:foreground "#242424" :background "SteelBlue1"))))
   `(custom-comment ((,class (:background "gray85"))))
   `(custom-comment-tag ((,class (:foreground "light blue"))))
   `(custom-documentation ((,class (nil))))
   `(custom-face-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold))))
   `(custom-group-tag ((,class (:height 1.2 :weight bold :foreground "SteelBlue1"))))
   `(custom-group-tag-1 ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "tomato2"))))
   `(custom-invalid ((,class (:foreground "gray20" :background "pink"))))
   `(custom-link ((,class (:underline t :foreground "SteelBlue1"))))
   `(custom-modified ((,class (:foreground "#242424" :background "SteelBlue1"))))
   `(custom-rogue ((,class (:foreground "pink" :background "#F6F3E8"))))
   `(custom-saved ((,class (:underline t))))
   `(custom-set ((,class (:foreground "SteelBlue1" :background "#242424"))))
   `(custom-state ((,class (:foreground "green3"))))
   `(custom-themed ((,class (:foreground "#242424" :background "SteelBlue1"))))
   `(custom-variable-button ((,class (:weight bold :underline t))))
   `(custom-variable-tag ((,class (:family "Sans Serif" :height 1.2 :weight bold :foreground "SteelBlue1"))))
   `(custom-visibility ((,class ,link)))
   `(diff-hl-change ((,class (:foreground "SteelBlue1" :inherit diff-changed))))
   `(diff-hl-delete ((,class (:foreground "tomato2" :inherit diff-removed))))
   `(diff-hl-dired-change ((,class (:weight bold :foreground "#F6F3E8" :background "LightGoldenrod"))))
   `(diff-hl-dired-delete ((,class (:weight bold :foreground "tomato2"))))
   `(diff-hl-dired-ignored ((,class (:weight bold :foreground "#242424" :background "gray50"))))
   `(diff-hl-dired-insert ((,class (:weight bold :foreground "gray50"))))
   `(diff-hl-dired-unknown ((,class (:foreground "#242424" :background "aquamarine"))))
   `(diff-hl-insert ((,class (:foreground "green3" :inherit diff-added))))
   `(diff-hl-unknown ((,class (:foreground "#242424" :background "aquamarine"))))
   `(diary-face ((,class (:foreground "SteelBlue1"))))
   `(dircolors-face-asm ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-backup ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-compress ((,class (:foreground "pink"))))
   `(dircolors-face-dir ((,class ,directory)))
   `(dircolors-face-doc ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-dos ((,class (:foreground "#CAE682"))))
   `(dircolors-face-emacs ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-exec ((,class (:foreground "#CAE682"))))
   `(dircolors-face-html ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-img ((,class (:foreground "#CC99CC"))))
   `(dircolors-face-lang ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-lang-interface ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-make ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-objet ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-package ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-paddb ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-ps ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-sound ((,class (:foreground "SteelBlue1"))))
   `(dircolors-face-tar ((,class (:foreground "pink"))))
   `(dircolors-face-text ((,class (:foreground "#F6F3E8"))))
   `(dircolors-face-yacc ((,class (:foreground "#F6F3E8"))))
   `(dired-directory ((,class ,directory)))
   `(dired-header ((,class ,directory)))
   `(dired-ignored ((,class (:strike-through t :foreground "pink"))))
   `(dired-mark ((,class ,marked-line)))
   `(dired-marked ((,class ,marked-line)))
   `(dired-symlink ((,class ,symlink)))
   `(diredp-compressed-file-suffix ((,class (:foreground "pink"))))
   `(diredp-date-time ((,class (:foreground "#CC99CC"))))
   `(diredp-dir-heading ((,class ,directory)))
   `(diredp-dir-priv ((,class ,directory)))
   `(diredp-exec-priv ((,class (:background "light green"))))
   `(diredp-executable-tag ((,class (:foreground "#CAE682" :background "#242424"))))
   `(diredp-file-name ((,class (:foreground "#F6F3E8"))))
   `(diredp-file-suffix ((,class (:foreground "#4BC98A"))))
   `(diredp-flag-mark-line ((,class ,marked-line)))
   `(diredp-ignored-file-name ((,class ,shadow)))
   `(diredp-read-priv ((,class (:background "light blue"))))
   `(diredp-write-priv ((,class (:foreground "#242424" :background "tomato2"))))
   `(evil-search-highlight-persist-highlight-face ((,class ,std-highlight)))
   `(file-name-shadow ((,class ,shadow)))
   `(font-latex-bold-face ((,class (:weight bold :foreground "#F6F3E8"))))
   `(font-latex-italic-face ((,class (:slant italic :foreground "gray95"))))
   `(font-latex-math-face ((,class (:foreground "SteelBlue1"))))
   `(font-latex-sectioning-1-face ((,class (:family "Sans Serif" :height 2.7 :weight bold :foreground "SteelBlue1"))))
   `(font-latex-sectioning-2-face ((,class ,ol1)))
   `(font-latex-sectioning-3-face ((,class ,ol2)))
   `(font-latex-sectioning-4-face ((,class ,ol3)))
   `(font-latex-sectioning-5-face ((,class ,ol4)))
   `(font-latex-sedate-face ((,class (:foreground "tomato2"))))
   `(font-latex-string-face ((,class (:weight bold :foreground "light blue"))))
   `(font-latex-verbatim-face ((,class (:foreground "gray60" :background "grey18" :inherit nil))))
   `(git-commit-summary-face ((,class (:foreground "#F6F3E8"))))
   `(git-commit-comment-face ((,class (:slant italic :foreground "SlateGray3"))))
   `(google-translate-text-face ((t (:foreground "#777777" :background "SlateGray3"))))
   `(google-translate-phonetic-face ((t (:inherit shadow))))
   `(google-translate-translation-face ((t (:weight normal :foreground "#64A8D8" :background "gray30"))))
   `(google-translate-suggestion-label-face ((t (:foreground "pink"))))
   `(google-translate-suggestion-face ((t (:slant italic :underline t))))
   `(google-translate-listen-button-face ((t (:height 0.8))))
   `(helm-action ((,class (:foreground "#F6F3E8"))))
   `(helm-bookmarks-su-face ((,class (:foreground "pink"))))
   `(helm-buffer-directory ((,class ,directory)))
   `(helm-buffer-process ((,class (:foreground "light green"))))
   `(helm-candidate-number ((,class (:foreground "#F6F3E8" :background "#CC99CC"))))
   `(helm-dir-heading ((,class (:foreground "SteelBlue1" :background "pink"))))
   `(helm-dir-priv ((,class (:foreground "red" :background "light grey"))))
   `(helm-ff-directory ((,class ,directory)))
   `(helm-ff-executable ((,class (:foreground "PaleGreen" :background "#242424"))))
   `(helm-ff-file ((,class (:foreground "#F6F3E8"))))
   `(helm-ff-invalid-symlink ((,class (:foreground "gray20" :background "pink"))))
   `(helm-ff-symlink ((,class ,symlink)))
   `(helm-file-name ((,class (:foreground "SteelBlue1"))))
   `(helm-gentoo-match-face ((,class (:foreground "pink"))))
   `(helm-grep-match ((,class ,match)))
   `(helm-grep-running ((,class (:weight bold :foreground "#242424"))))
   `(helm-grep-lineno ((,class ,shadow)))
   `(helm-isearch-match ((,class (:background "#4BC98A"))))
   `(helm-match ((,class ,match)))
   `(helm-moccur-buffer ((,class (:foreground "SteelBlue1"))))
   `(helm-selection ((,class ,volatile-highlight)))
   `(helm-selection-line ((,class ,volatile-highlight)))
   `(helm-lisp-show-completion ((,class ,volatile-highlight))) ; see `helm-dabbrev'
   `(helm-source-header ((,class (:family "Sans Serif" :height 1.3 :weight bold :foreground "#242424" :background "#64A8D8"))))
   `(helm-swoop-target-line-face ((,class ,volatile-highlight)))
   `(helm-swoop-target-line-block-face ((,class (:background "light green" :foreground "gray70"))))
   `(helm-swoop-target-word-face ((,class (:weight bold :foreground nil :background "SlateGray3"))))
   `(helm-visible-mark ((,class ,marked-line)))
   `(helm-w3m-bookmarks-face ((,class (:underline t :foreground "cyan"))))
   `(highlight-symbol-face ((,class (:background "SlateGray3"))))
   `(hl-line ((,class ,highlight-line)))
   `(hl-tags-face ((,class (:background "gray22"))))
   `(holiday-face ((,class (:foreground "#777777" :background "#FFC125"))))
   `(html-helper-bold-face ((,class (:weight bold :foreground "#F6F3E8"))))
   `(html-helper-italic-face ((,class (:slant italic :foreground "#F6F3E8"))))
   `(html-helper-underline-face ((,class (:underline t :foreground "#F6F3E8"))))
   `(html-tag-face ((,class (:foreground "SteelBlue1"))))
   `(ilog-non-change-face ((,class (:height 2.0 :foreground "plum"))))
   `(ilog-change-face ((,class (:height 2.0 :foreground "light green"))))
   `(ilog-echo-face ((,class (:height 2.0 :foreground "SteelBlue1"))))
   `(ilog-load-face ((,class (:foreground "#CAE682"))))
   `(ilog-message-face ((,class (:foreground "#808080"))))
   `(info-file ((,class (:family "Sans Serif" :height 1.8 :weight bold :box (:line-width 1 :color "SteelBlue1") :foreground "SteelBlue1" :background "gray70"))))
   `(info-header-node ((,class (:underline t :foreground "#E65C00")))) ; nodes in header
   `(info-header-xref ((,class (:underline t :foreground "SteelBlue1")))) ; cross references in header
   `(info-index-match ((,class (:weight bold :foreground nil :background "SlateGray3")))) ; when using `i'
   `(info-menu-header ((,class ,ol2))) ; menu titles (headers) -- major topics
   `(info-menu-star ((,class (:foreground "#F6F3E8")))) ; every 3rd menu item
   `(info-node ((,class (:underline t :foreground "SteelBlue1")))) ; node names
   `(info-quoted-name ((,class ,code-inline)))
   `(info-string ((,class ,string)))
   `(info-title-1 ((,class ,ol1)))
   `(info-xref ((,class (:underline t :foreground "#8AC6F2")))) ; unvisited cross-references
   `(info-xref-visited ((,class (:underline t :foreground "#C99CC")))) ; previously visited cross-references
   `(light-symbol-face ((,class (:background "SlateGray3"))))
   `(linum ((,class ,side)))
   `(log-view-file ((,class (:foreground "SteelBlue1" :background "grey18"))))
   `(log-view-message ((,class (:foreground "PaleGreen"))))
   `(lui-button-face ((,class ,link)))
   `(lui-highlight-face ((,class (:box '(:line-width 1 :color "tomato2") :foreground "tomato2" :background "gray18")))) ; my nickname
   `(lui-time-stamp-face ((,class (:foreground "#CC99CC"))))
   `(magit-blame-header ((,class (:inherit magit-diff-file-header))))
   `(magit-branch ((,class ,vc-branch)))
   `(magit-diff-add ((,class ,diff-added)))
   `(magit-diff-del ((,class ,diff-removed)))
   `(magit-diff-file-header ((,class (:family "Sans Serif" :height 1.1 :weight bold :foreground "SteelBlue1"))))
   `(magit-diff-hunk-header ((,class ,diff-hunk-header)))
   `(magit-diff-none ((,class ,diff-none)))
   `(magit-header ((,class (:foreground "#242424" :background "tomato2"))))
   `(magit-item-highlight ((,class (:background "grey18"))))
   `(magit-item-mark ((,class ,marked-line)))
   `(magit-log-head-label ((,class (:box (:line-width 1 :color "SteelBlue1" :style nil)))))
   `(magit-log-tag-label ((,class (:box (:line-width 1 :color "#CAE682" :style nil)))))
   `(magit-section-title ((,class (:family "Sans Serif" :height 1.8 :weight bold :foreground "SteelBlue1" :inherit nil))))
   `(makefile-space-face ((,class (:background "pink"))))
   `(makefile-targets ((,class (:weight bold :foreground "SteelBlue1"))))
   `(match ((,class ,match)))           ; Used for grep matches.
   `(mm-uu-extract ((,class ,code-block)))
   `(moccur-current-line-face ((,class (:foreground "#F6F3E8" :background "#FFFFCC"))))
   `(moccur-face ((,class (:foreground "#F6F3E8" :background "SlateGray3"))))
   `(next-error ((,class ,volatile-highlight)))
   `(nobreak-space ((,class (:background "SteelBlue1"))))
   `(nxml-attribute-local-name-face ((,class (:foreground "plum"))))
   `(nxml-attribute-value-delimiter-face ((,class (:foreground "green3"))))
   `(nxml-attribute-value-face ((,class (:foreground "green3"))))
   `(nxml-comment-content-face ((,class (:slant italic :foreground "pink"))))
   `(nxml-comment-delimiter-face ((,class (:foreground "pink"))))
   `(nxml-element-local-name ((,class (:box (:line-width 1 :color "#999999") :foreground "gray60" :background "gray30"))))
   `(nxml-element-local-name-face ((,class (:foreground "SteelBlue1"))))
   `(nxml-processing-instruction-target-face ((,class (:foreground "#CC99CC"))))
   `(nxml-tag-delimiter-face ((,class (:foreground "SteelBlue1"))))
   `(nxml-tag-slash-face ((,class (:foreground "SteelBlue1"))))
   ;; `(org-agenda-block-count ((,class (:weight bold :foreground "gray50"))))
   `(org-agenda-calendar-event ((,class (:inherit default))))
   `(org-agenda-calendar-sexp ((,class (:inherit default))))
   `(org-agenda-clocking ((,class (:inherit secondary-selection))))
   `(org-agenda-column-dateline ((,class ,column)))
   `(org-agenda-current-time ((,class (:inherit org-time-grid))))
   `(org-agenda-date ((,class (:height 1.3 :weight bold :inherit org-agenda-structure))))
   `(org-agenda-date-today ((,class (:inherit org-agenda-date))))
   `(org-agenda-date-weekend ((,class (:inherit org-agenda-date))))
   `(org-agenda-diary ((,class (:inherit default))))
   `(org-agenda-dimmed-todo-face ((,class (:foreground "gray50"))))
   `(org-agenda-done ((,class (:foreground "PaleGreen"))))
   `(org-agenda-filter-category ((,class (:inherit mode-line))))
   `(org-agenda-filter-tags ((,class (:weight bold :foreground "#E65C00"))))
   `(org-agenda-restriction-lock ((,class (:inherit mode-line))))
   `(org-agenda-structure ((,class (:height 1.3 :weight bold :foreground "LightSkyBlue"))))
   `(org-archived ((,class (:inherit shadow))))
   ;; `(org-beamer-tag ((,class (:box (:line-width 1 :color "LightGoldenrod1") :foreground "gray90" :background "PaleGreen"))))
   `(org-block ((,class ,code-block)))
   `(org-block-background ((,class (:background "grey12"))))
   `(org-block-begin-line ((,class ,code-block-begin)))
   `(org-block-end-line ((,class ,code-block-end)))
   `(org-checkbox ((,class (:box (:line-width 1 :style released-button) :foreground "gray90" :background "gray24"))))
   `(org-clock-overlay ((,class (:background "SkyBlue"))))
   `(org-code ((,class ,code-inline)))
   `(org-column ((,class ,column)))
   `(org-column-title ((,class ,column)))
   `(org-date ((,class (:underline t :foreground "SkyBlue1"))))
   `(org-default ((,class (:inherit default))))
   `(org-dim ((,class (:foreground "gray50"))))
   `(org-document-info ((,class (:foreground "pale turquoise"))))
   `(org-document-info-keyword ((,class (:inherit shadow))))
   `(org-document-title ((,class (:family "Sans Serif" :height 1.6 :weight bold :foreground "#F6F3E8"))))
   `(org-done ((,class (:weight bold :foreground "PaleGreen"))))
   `(org-drawer ((,class (:foreground "LightSkyBlue"))))
   `(org-ellipsis ((,class (:underline t :foreground "LightGoldenrod")))) ; #FFEE62
   `(org-example ((,class (:foreground "SteelBlue1"))))
   `(org-footnote ((,class (:underline t :foreground "SkyBlue1"))))
   `(org-formula ((,class (:foreground "chocolate"))))
   `(org-headline-done ((,class (:foreground "LightSalmon"))))
   `(org-hide ((,class (:foreground "#242424"))))
   `(org-inlinetask ((,class (:foreground "#777777" :background "SlateGray3"))))
   `(org-latex-and-related ((,class (:foreground "burlywood"))))
   `(org-level-1 ((,class ,ol1)))
   `(org-level-2 ((,class ,ol2)))
   `(org-level-3 ((,class ,ol3)))
   `(org-level-4 ((,class ,ol4)))
   `(org-level-5 ((,class ,ol5)))
   `(org-level-6 ((,class ,ol6)))
   `(org-level-7 ((,class ,ol7)))
   `(org-level-8 ((,class ,ol8)))
   `(org-link ((,class ,link)))
   `(org-list-dt ((,class (:weight bold))))
   `(org-macro ((,class (:inherit org-latex-and-related))))
   `(org-meta-line ((,class (:inherit font-lock-comment-face))))
   `(org-mode-line-clock ((,class ,clock-line)))
   `(org-mode-line-clock-overrun ((,class (:weight bold :box (:line-width 1 :color "#335EA8") :foreground "#242424" :background "tomato2" :inherit mode-line))))
   `(org-number-of-items ((,class (:weight bold :foreground "#242424"))))
   ;; `(org-property-value ((,class (:foreground "#CAE682"))))
   `(org-priority ((,class (:inherit font-lock-keyword-face))))
   `(org-quote ((,class (:slant italic :inherit org-block))))
   `(org-scheduled ((,class (:foreground "PaleGreen"))))
   `(org-scheduled-previously ((,class (:foreground "tomato2"))))
   `(org-scheduled-today ((,class (:weight bold :foreground "PaleGreen"))))
   `(org-sexp-date ((,class (:foreground "SteelBlue1"))))
   `(org-special-keyword ((,class (:weight bold :inherit font-lock-keyword-face))))
   `(org-table ((,class (:foreground "LightSkyBlue"))))
   `(org-tag ((,class (:slant italic :foreground "gray40"))))
   `(org-target ((,class (:underline t))))
   `(org-time-grid ((,class (:foreground "LightGoldenrod"))))
   `(org-todo ((,class (:weight bold :foreground "pink"))))
   `(org-upcoming-deadline ((,class (:foreground "chocolate1"))))
   `(org-verbatim ((,class (:foreground "SteelBlue1"))))
   `(org-verse ((,class (:slant italic :inherit org-block))))
   `(org-warning ((,class (:inherit font-lock-warning-face))))
   `(outline-1 ((,class ,ol1)))
   `(outline-2 ((,class ,ol2)))
   `(outline-3 ((,class ,ol3)))
   `(outline-4 ((,class ,ol4)))
   `(outline-5 ((,class ,ol5)))
   `(outline-6 ((,class ,ol6)))
   `(outline-7 ((,class ,ol7)))
   `(outline-8 ((,class ,ol8)))
   `(pabbrev-debug-display-label-face ((,class (:background "#4BC98A"))))
   `(pabbrev-suggestions-face ((,class (:weight bold :foreground "#242424" :background "pink"))))
   `(pabbrev-suggestions-label-face ((,class (:weight bold :foreground "#242424" :background "#CC99CC"))))
   `(paren-face-match ((,class ,paren-matched)))
   `(paren-face-mismatch ((,class ,paren-unmatched)))
   `(paren-face-no-match ((,class ,paren-unmatched)))
   `(persp-selected-face ((,class (:weight bold :foreground "gray70"))))
   `(powerline-active1 ((,class (:background "grey20" :inherit mode-line))))
   `(powerline-active2 ((,class (:background "gray40" :inherit mode-line))))
   `(powerline-inactive1 ((,class (:background "gray11" :inherit mode-line-inactive))))
   `(powerline-inactive2 ((,class (:background "gray20" :inherit mode-line-inactive))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground "gray50"))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground "SteelBlue1"))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground "gray50"))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground "light green"))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground "pink"))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground "SlateGray2"))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground "gray50"))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground "light green"))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground "gray50"))))
   `(rainbow-delimiters-mismatched-face ((,class ,paren-unmatched)))
   `(rainbow-delimiters-unmatched-face ((,class ,paren-unmatched)))
   `(recover-this-file ((,class (:weight bold :background "tomato2"))))
   `(rng-error ((,class (:weight bold :foreground "pink" :background "pink"))))
   `(sh-heredoc ((,class (:foreground "SteelBlue1" :background "gray70"))))
   `(sh-quoted-exec ((,class (:foreground "pink"))))
   `(shadow ((,class ,shadow)))         ; Used for grep context lines.
   `(shell-option-face ((,class (:foreground "#CAE682"))))
   `(shell-output-2-face ((,class (:foreground "SteelBlue1"))))
   `(shell-output-3-face ((,class (:foreground "#CC99CC"))))
   `(shell-output-face ((,class (:foreground "#F6F3E8"))))
   ;; `(shell-prompt-face ((,class (:weight bold :foreground "gray20"))))
   `(shm-current-face ((,class (:background "gray24"))))
   `(shm-quarantine-face ((,class (:background "LightGoldenrod3"))))
   `(show-paren-match ((,class ,paren-matched)))
   `(show-paren-mismatch ((,class ,paren-unmatched)))
   `(sml-modeline-end-face ((,class (:background "light blue")))) ; #335EA8
   `(sml-modeline-vis-face ((,class (:background "#64A8D8"))))
   `(speedbar-button-face ((,class (:foreground "green3"))))
   `(speedbar-directory-face ((,class (:foreground "light blue"))))
   `(speedbar-file-face ((,class (:foreground "cyan"))))
   `(speedbar-highlight-face ((,class ,volatile-highlight)))
   `(speedbar-selected-face ((,class (:underline t :foreground "pink"))))
   `(speedbar-tag-face ((,class (:foreground "LightGoldenrod1"))))
   `(svn-status-directory-face ((,class ,directory)))
   `(svn-status-filename-face ((,class (:weight bold :foreground "SteelBlue1"))))
   `(svn-status-locked-face ((,class (:weight bold :foreground "pink"))))
   `(svn-status-marked-face ((,class ,marked-line)))
   `(svn-status-marked-popup-face ((,class (:weight bold :foreground "PaleGreen"))))
   `(svn-status-switched-face ((,class (:slant italic :foreground "gray55"))))
   `(svn-status-symlink-face ((,class ,symlink)))
   `(svn-status-update-available-face ((,class (:foreground "#E65C00"))))
   `(tex-verbatim ((,class (:foreground "SteelBlue1"))))
   `(tool-bar ((,class (:box (:line-width 1 :style released-button) :foreground "#F6F3E8" :background "gray75"))))
   `(tooltip ((,class (:foreground "#F6F3E8" :background "yellow4"))))
   `(trailing-whitespace ((,class (:background "SlateGray3"))))
   `(traverse-match-face ((,class (:weight bold :foreground "#F283B6"))))
   `(vc-annotate-face-3F3FFF ((,class (:foreground "#64A8D8" :background "#F6F3E8"))))
   `(vc-annotate-face-3F6CFF ((,class (:foreground "#64A8D8" :background "#F6F3E8"))))
   `(vc-annotate-face-3F99FF ((,class (:foreground "aquamarine" :background "#F6F3E8"))))
   `(vc-annotate-face-3FC6FF ((,class (:foreground "aquamarine" :background "#F6F3E8"))))
   `(vc-annotate-face-3FF3FF ((,class (:foreground "cyan" :background "#F6F3E8"))))
   `(vc-annotate-face-3FFF56 ((,class (:foreground "light green" :background "#F6F3E8"))))
   `(vc-annotate-face-3FFF83 ((,class (:foreground "#CAE682" :background "#F6F3E8"))))
   `(vc-annotate-face-3FFFB0 ((,class (:foreground "#CAE682" :background "#F6F3E8"))))
   `(vc-annotate-face-3FFFDD ((,class (:foreground "cyan" :background "#F6F3E8"))))
   `(vc-annotate-face-56FF3F ((,class (:foreground "light green" :background "#F6F3E8"))))
   `(vc-annotate-face-83FF3F ((,class (:foreground "forest green" :background "#F6F3E8"))))
   `(vc-annotate-face-B0FF3F ((,class (:foreground "forest green" :background "#F6F3E8"))))
   `(vc-annotate-face-DDFF3F ((,class (:foreground "pink" :background "#F6F3E8"))))
   `(vc-annotate-face-FF3F3F ((,class (:foreground "tomato2" :background "#F6F3E8"))))
   `(vc-annotate-face-FF6C3F ((,class (:foreground "tomato2" :background "#F6F3E8"))))
   `(vc-annotate-face-FF993F ((,class (:foreground "#FFC125" :background "#F6F3E8"))))
   `(vc-annotate-face-FFC63F ((,class (:foreground "#FFC125" :background "#F6F3E8"))))
   `(vc-annotate-face-FFF33F ((,class (:foreground "pink" :background "#F6F3E8"))))
   `(w3m-anchor ((,class ,link)))
   `(w3m-arrived-anchor ((,class (:foreground "#CC99CC"))))
   `(w3m-bitmap-image-face ((,class (:foreground "gray90" :background "#95e454"))))
   `(w3m-bold ((,class (:weight bold :foreground "#F6F3E8"))))
   `(w3m-current-anchor ((,class (:weight bold :underline t :foreground "SteelBlue1"))))
   `(w3m-form ((,class (:underline t :foreground "tan4"))))
   `(w3m-form-button-face ((,class (:weight bold :underline t :foreground "gray90" :background "light grey"))))
   `(w3m-form-button-mouse-face ((,class (:underline t :foreground "light grey" :background "#95E454"))))
   `(w3m-form-button-pressed-face ((,class (:weight bold :underline t :foreground "gray90" :background "light grey"))))
   `(w3m-header-line-location-content-face ((,class (:foreground "gray70":background "gray20"))))
   `(w3m-header-line-location-title-face ((,class (:foreground "#64A8D8" :background "gray20"))))
   `(w3m-history-current-url-face ((,class (:foreground "#F57900"))))
   `(w3m-image-face ((,class (:weight bold :foreground "#4BC98A"))))
   `(w3m-link-numbering ((,class (:foreground "SteelBlue1")))) ; mouseless browsing
   `(w3m-strike-through-face ((,class (:strike-through t))))
   `(w3m-underline-face ((,class (:underline t))))
   `(which-func ((,class (:weight bold :foreground "#242424"))))
   `(widget-button ((,class ,link)))
   `(widget-button-pressed ((,class (:foreground "pink"))))
   `(widget-documentation ((,class (:foreground "green3"))))
   `(widget-field ((,class (:background "gray85"))))
   `(widget-inactive ((,class (:foreground "gray70"))))
   `(widget-single-line-field ((,class (:background "gray85"))))
   `(yas/field-debug-face ((,class (:background "gray"))))
   `(yas/field-highlight-face ((,class (:background "#4BC98A"))))
   ))

(custom-theme-set-variables 'leuven-dark
                            '(ansi-color-faces-vector
                              [default default default italic underline success warning error])
                            '(ansi-color-names-vector
                              ["#F6F3E8" "tomato2" "#CAE682" "PaleGreen" "SteelBlue1" "#CC99CC" "SteelBlue1" "gray50"])
                                        ; colors used in Shell mode
                            )

;;;###autoload
(when (and (boundp 'custom-theme-load-path)
           load-file-name)
  ;; add theme folder to `custom-theme-load-path' when installing over MELPA
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'leuven-dark)

;; This is for the sake of Emacs.
;; Local Variables:
;; no-byte-compile: t
;; time-stamp-end: "$"
;; time-stamp-format: "%:y%02m%02d.%02H%02M"
;; time-stamp-start: "Version: "
;; End:

;;; leuven-dark-theme.el ends here
